Repository codeforpublic/SQUID, pull requests merged in 2021-01, with the labels that each got.

#65 Start GeoLocation only on iPhone and Android with GMS enabled
  package.json
  src/services/background-tracking.ts
  yarn.lock
Labels: bug

#66 Fix localization on onboard complete screen
  src/navigations/2-Onboarding/OnboardComplete.tsx
Labels: bug

#68 Fix podfile.lock didn't get updated during upgrade RNDeviceInfo
  ios/Podfile.lock
Labels: bug

#72 Add CODE_OF_CONDUCT
  CODE_OF_CONDUCT.md
Labels: documentation

#70 Automatically generate a debug APK on GitHub Actions
  .github/workflows/build-android-debug.yml
  docker-compose.yml
Labels: internal
